version: '3.7'

services:

  tradecube-services:
    image: tradecube-services
    build:
      context: src
      dockerfile: TradeCube-Services/Dockerfile
    ports:
      - 44350:44350
      - 44365:44365
    volumes:
      - /foldercontainingcerts:/certs      
      - /tmp:/tmp      
    expose:
      - 44350
      - 44365
    environment: 
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'TRADECUBE_API_DOMAIN=https://api-int.ctrmcubed.com/'
      - 'TRADECUBE_API_PORT=44390'
      - 'TRADECUBE_SERVICES_HTTPS_PORT=44350'
      - 'TRADECUBE_SERVICES_CERT_NAME=/certs/certname.pfx'
      - 'TRADECUBE_SERVICES_CERT_PASSWORD=certpassword'
      - 'JSREPORT_DOMAIN=http://reports.ctrmcubed.com'      
      - 'JSREPORT_PORT=80'      