//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Equias.Models.Bcn {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Reason {
        
        private ReasonCodeType reasonCodeField;
        
        private string errorSourceField;
        
        private string originatorField;
        
        private string reasonTextField;
        
        /// <remarks/>
        public ReasonCodeType ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorSource {
            get {
                return this.errorSourceField;
            }
            set {
                this.errorSourceField = value;
            }
        }
        
        /// <remarks/>
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonText {
            get {
                return this.reasonTextField;
            }
            set {
                this.reasonTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum ReasonCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("XML:ValidationFailure")]
        XMLValidationFailure,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:ValueNotRecognized")]
        ebxmlValueNotRecognized,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:NotSupported")]
        ebxmlNotSupported,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:Inconsistent")]
        ebxmlInconsistent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:OtherXML")]
        ebxmlOtherXML,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:DeliveryFailure")]
        ebxmlDeliveryFailure,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:TimeToLiveExpired")]
        ebxmlTimeToLiveExpired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:SecurityFailure")]
        ebxmlSecurityFailure,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:MimeProblem")]
        ebxmlMimeProblem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ebxml:Unknown")]
        ebxmlUnknown,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:InvalidData")]
        efetInvalidData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:TimeOut")]
        efetTimeOut,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:InvalidMatchAttempt")]
        efetInvalidMatchAttempt,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:AmendmentError")]
        efetAmendmentError,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:IDNotFound")]
        efetIDNotFound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:UniquenessViolation")]
        efetUniquenessViolation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:NoMatch")]
        efetNoMatch,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:ReferencedDocNotExists")]
        efetReferencedDocNotExists,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:RefDocInvalidState")]
        efetRefDocInvalidState,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("efet:MinorVersionInInvalidState")]
        efetMinorVersionInInvalidState,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public partial class CurrencyCodeTypeWithFractionOption {
        
        private bool useFractionUnitField;
        
        private string valueField;
        
        public CurrencyCodeTypeWithFractionOption() {
            this.useFractionUnitField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UseFractionUnit {
            get {
                return this.useFractionUnitField;
            }
            set {
                this.useFractionUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="NMTOKEN")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("CommonPricing", Namespace="", IsNullable=false)]
    public enum CommonPricingType {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FixedPriceInformation {
        
        private string fixedPricePayerField;
        
        private string fPCurrencyUnitField;
        
        private UnitOfMeasureType fPCapacityUnitField;
        
        private bool fPCapacityUnitFieldSpecified;
        
        private decimal fPCapacityConversionRateField;
        
        private bool fPCapacityConversionRateFieldSpecified;
        
        private FXInformation fXInformationField;
        
        /// <remarks/>
        public string FixedPricePayer {
            get {
                return this.fixedPricePayerField;
            }
            set {
                this.fixedPricePayerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string FPCurrencyUnit {
            get {
                return this.fPCurrencyUnitField;
            }
            set {
                this.fPCurrencyUnitField = value;
            }
        }
        
        /// <remarks/>
        public UnitOfMeasureType FPCapacityUnit {
            get {
                return this.fPCapacityUnitField;
            }
            set {
                this.fPCapacityUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FPCapacityUnitSpecified {
            get {
                return this.fPCapacityUnitFieldSpecified;
            }
            set {
                this.fPCapacityUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal FPCapacityConversionRate {
            get {
                return this.fPCapacityConversionRateField;
            }
            set {
                this.fPCapacityConversionRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FPCapacityConversionRateSpecified {
            get {
                return this.fPCapacityConversionRateFieldSpecified;
            }
            set {
                this.fPCapacityConversionRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FXInformation FXInformation {
            get {
                return this.fXInformationField;
            }
            set {
                this.fXInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum UnitOfMeasureType {
        
        /// <remarks/>
        Therm,
        
        /// <remarks/>
        KWh,
        
        /// <remarks/>
        MWh,
        
        /// <remarks/>
        GWh,
        
        /// <remarks/>
        MJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100MJ")]
        Item100MJ,
        
        /// <remarks/>
        MMJ,
        
        /// <remarks/>
        GJ,
        
        /// <remarks/>
        BBL,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        GAL,
        
        /// <remarks/>
        ThermPerDay,
        
        /// <remarks/>
        KWhPerDay,
        
        /// <remarks/>
        GWhPerDay,
        
        /// <remarks/>
        MJPerDay,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100MJPerDay")]
        Item100MJPerDay,
        
        /// <remarks/>
        MMJPerDay,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        GJPerDay,
        
        /// <remarks/>
        Day,
        
        /// <remarks/>
        EUA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FXInformation {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FXMethod", typeof(FXConversionMethodType))]
        [System.Xml.Serialization.XmlElementAttribute("FXRate", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("FXReference", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum FXConversionMethodType {
        
        /// <remarks/>
        Daily,
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        Mixed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Rounding", Namespace="", IsNullable=false)]
    public enum RoundingType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        N_A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BrokerConfirmation {
        
        private string documentIDField;
        
        private UsageType documentUsageField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private RoleType receiverRoleField;
        
        private string documentVersionField;
        
        private string marketField;
        
        private EnergyProductType commodityField;
        
        private bool commodityFieldSpecified;
        
        private TransactionType transactionTypeField;
        
        private string deliveryPointAreaField;
        
        private string buyerPartyField;
        
        private string sellerPartyField;
        
        private ContractType loadTypeField;
        
        private bool loadTypeFieldSpecified;
        
        private string agreementField;
        
        private CurrencyCodeTypeWithFractionOption currencyField;
        
        private decimal totalVolumeField;
        
        private UnitOfMeasureType totalVolumeUnitField;
        
        private System.DateTime tradeDateField;
        
        private UnitOfMeasureType capacityUnitField;
        
        private bool capacityUnitFieldSpecified;
        
        private BrokerConfirmationPriceUnit priceUnitField;
        
        private BrokerConfirmationTimeIntervalQuantity[] timeIntervalQuantitiesField;
        
        private FixedPriceInformation fixedPriceInformationField;
        
        private object[] itemsField;
        
        private CommonPricingType commonPricingField;
        
        private bool commonPricingFieldSpecified;
        
        private System.DateTime effectiveDateField;
        
        private bool effectiveDateFieldSpecified;
        
        private System.DateTime terminationDateField;
        
        private bool terminationDateFieldSpecified;
        
        private BrokerConfirmationEUATradeDetails eUATradeDetailsField;
        
        private BrokerConfirmationPhysicalCoalTradeDetails physicalCoalTradeDetailsField;
        
        private BrokerConfirmationHubCodificationInformation hubCodificationInformationField;
        
        private BrokerConfirmationOptionDetails optionDetailsField;
        
        private BrokerConfirmationDeliveryPeriod[] deliveryPeriodsField;
        
        private BrokerConfirmationAgent[] agentsField;
        
        private System.DateTime tradeTimeField;
        
        private bool tradeTimeFieldSpecified;
        
        private string traderNameField;
        
        private string schemaVersionField;
        
        private string schemaReleaseField;
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public UsageType DocumentUsage {
            get {
                return this.documentUsageField;
            }
            set {
                this.documentUsageField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        public RoleType ReceiverRole {
            get {
                return this.receiverRoleField;
            }
            set {
                this.receiverRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string Market {
            get {
                return this.marketField;
            }
            set {
                this.marketField = value;
            }
        }
        
        /// <remarks/>
        public EnergyProductType Commodity {
            get {
                return this.commodityField;
            }
            set {
                this.commodityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommoditySpecified {
            get {
                return this.commodityFieldSpecified;
            }
            set {
                this.commodityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TransactionType TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryPointArea {
            get {
                return this.deliveryPointAreaField;
            }
            set {
                this.deliveryPointAreaField = value;
            }
        }
        
        /// <remarks/>
        public string BuyerParty {
            get {
                return this.buyerPartyField;
            }
            set {
                this.buyerPartyField = value;
            }
        }
        
        /// <remarks/>
        public string SellerParty {
            get {
                return this.sellerPartyField;
            }
            set {
                this.sellerPartyField = value;
            }
        }
        
        /// <remarks/>
        public ContractType LoadType {
            get {
                return this.loadTypeField;
            }
            set {
                this.loadTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoadTypeSpecified {
            get {
                return this.loadTypeFieldSpecified;
            }
            set {
                this.loadTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
        
        /// <remarks/>
        public CurrencyCodeTypeWithFractionOption Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalVolume {
            get {
                return this.totalVolumeField;
            }
            set {
                this.totalVolumeField = value;
            }
        }
        
        /// <remarks/>
        public UnitOfMeasureType TotalVolumeUnit {
            get {
                return this.totalVolumeUnitField;
            }
            set {
                this.totalVolumeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime TradeDate {
            get {
                return this.tradeDateField;
            }
            set {
                this.tradeDateField = value;
            }
        }
        
        /// <remarks/>
        public UnitOfMeasureType CapacityUnit {
            get {
                return this.capacityUnitField;
            }
            set {
                this.capacityUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CapacityUnitSpecified {
            get {
                return this.capacityUnitFieldSpecified;
            }
            set {
                this.capacityUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public BrokerConfirmationPriceUnit PriceUnit {
            get {
                return this.priceUnitField;
            }
            set {
                this.priceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TimeIntervalQuantity", IsNullable=false)]
        public BrokerConfirmationTimeIntervalQuantity[] TimeIntervalQuantities {
            get {
                return this.timeIntervalQuantitiesField;
            }
            set {
                this.timeIntervalQuantitiesField = value;
            }
        }
        
        /// <remarks/>
        public FixedPriceInformation FixedPriceInformation {
            get {
                return this.fixedPriceInformationField;
            }
            set {
                this.fixedPriceInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FloatPriceInformation", typeof(BrokerConfirmationFloatPriceInformation))]
        [System.Xml.Serialization.XmlElementAttribute("TotalContractValue", typeof(decimal))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public CommonPricingType CommonPricing {
            get {
                return this.commonPricingField;
            }
            set {
                this.commonPricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommonPricingSpecified {
            get {
                return this.commonPricingFieldSpecified;
            }
            set {
                this.commonPricingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveDateSpecified {
            get {
                return this.effectiveDateFieldSpecified;
            }
            set {
                this.effectiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime TerminationDate {
            get {
                return this.terminationDateField;
            }
            set {
                this.terminationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TerminationDateSpecified {
            get {
                return this.terminationDateFieldSpecified;
            }
            set {
                this.terminationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public BrokerConfirmationEUATradeDetails EUATradeDetails {
            get {
                return this.eUATradeDetailsField;
            }
            set {
                this.eUATradeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public BrokerConfirmationPhysicalCoalTradeDetails PhysicalCoalTradeDetails {
            get {
                return this.physicalCoalTradeDetailsField;
            }
            set {
                this.physicalCoalTradeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public BrokerConfirmationHubCodificationInformation HubCodificationInformation {
            get {
                return this.hubCodificationInformationField;
            }
            set {
                this.hubCodificationInformationField = value;
            }
        }
        
        /// <remarks/>
        public BrokerConfirmationOptionDetails OptionDetails {
            get {
                return this.optionDetailsField;
            }
            set {
                this.optionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DeliveryPeriod", IsNullable=false)]
        public BrokerConfirmationDeliveryPeriod[] DeliveryPeriods {
            get {
                return this.deliveryPeriodsField;
            }
            set {
                this.deliveryPeriodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Agent", IsNullable=false)]
        public BrokerConfirmationAgent[] Agents {
            get {
                return this.agentsField;
            }
            set {
                this.agentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime TradeTime {
            get {
                return this.tradeTimeField;
            }
            set {
                this.tradeTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TradeTimeSpecified {
            get {
                return this.tradeTimeFieldSpecified;
            }
            set {
                this.tradeTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TraderName {
            get {
                return this.traderNameField;
            }
            set {
                this.traderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SchemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SchemaRelease {
            get {
                return this.schemaReleaseField;
            }
            set {
                this.schemaReleaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum UsageType {
        
        /// <remarks/>
        Test,
        
        /// <remarks/>
        Live,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum RoleType {
        
        /// <remarks/>
        Trader,
        
        /// <remarks/>
        Broker,
        
        /// <remarks/>
        ClearingHouse,
        
        /// <remarks/>
        ECVNA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum EnergyProductType {
        
        /// <remarks/>
        Power,
        
        /// <remarks/>
        Gas,
        
        /// <remarks/>
        Oil,
        
        /// <remarks/>
        Coal,
        
        /// <remarks/>
        ReactivePower,
        
        /// <remarks/>
        EUAPhase_1,
        
        /// <remarks/>
        EUAPhase_2,
        
        /// <remarks/>
        EUAPhase_3,
        
        /// <remarks/>
        CER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum TransactionType {
        
        /// <remarks/>
        DAH,
        
        /// <remarks/>
        IND,
        
        /// <remarks/>
        FOR,
        
        /// <remarks/>
        OPT,
        
        /// <remarks/>
        PHYS_INX,
        
        /// <remarks/>
        OPT_PHYS_INX,
        
        /// <remarks/>
        FXD_SWP,
        
        /// <remarks/>
        FLT_SWP,
        
        /// <remarks/>
        OPT_FXD_SWP,
        
        /// <remarks/>
        OPT_FLT_SWP,
        
        /// <remarks/>
        OPT_FIN_INX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum ContractType {
        
        /// <remarks/>
        Base,
        
        /// <remarks/>
        Peak,
        
        /// <remarks/>
        OffPeak,
        
        /// <remarks/>
        Custom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationPriceUnit {
        
        private CurrencyCodeTypeWithFractionOption currencyField;
        
        private UnitOfMeasureType capacityUnitField;
        
        /// <remarks/>
        public CurrencyCodeTypeWithFractionOption Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public UnitOfMeasureType CapacityUnit {
            get {
                return this.capacityUnitField;
            }
            set {
                this.capacityUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationTimeIntervalQuantity {
        
        private System.DateTime deliveryStartDateAndTimeField;
        
        private System.DateTime deliveryEndDateAndTimeField;
        
        private decimal contractCapacityField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        /// <remarks/>
        public System.DateTime DeliveryStartDateAndTime {
            get {
                return this.deliveryStartDateAndTimeField;
            }
            set {
                this.deliveryStartDateAndTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeliveryEndDateAndTime {
            get {
                return this.deliveryEndDateAndTimeField;
            }
            set {
                this.deliveryEndDateAndTimeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ContractCapacity {
            get {
                return this.contractCapacityField;
            }
            set {
                this.contractCapacityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationFloatPriceInformation {
        
        private string floatPricePayerField;
        
        private BrokerConfirmationFloatPriceInformationCommodityReference[] commodityReferencesField;
        
        /// <remarks/>
        public string FloatPricePayer {
            get {
                return this.floatPricePayerField;
            }
            set {
                this.floatPricePayerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CommodityReference", IsNullable=false)]
        public BrokerConfirmationFloatPriceInformationCommodityReference[] CommodityReferences {
            get {
                return this.commodityReferencesField;
            }
            set {
                this.commodityReferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationFloatPriceInformationCommodityReference {
        
        private string commodityReferencePriceField;
        
        private IndexCommodityType indexCommodityField;
        
        private string indexCurrencyUnitField;
        
        private UnitOfMeasureType indexCapacityUnitField;
        
        private decimal factorField;
        
        private decimal multiplierField;
        
        private bool multiplierFieldSpecified;
        
        private decimal indexCapField;
        
        private bool indexCapFieldSpecified;
        
        private decimal indexFloorField;
        
        private bool indexFloorFieldSpecified;
        
        private decimal cRCapacityConversionRateField;
        
        private bool cRCapacityConversionRateFieldSpecified;
        
        private FXInformation fXInformationField;
        
        private BrokerConfirmationFloatPriceInformationCommodityReferenceSpreadInformation spreadInformationField;
        
        private BrokerConfirmationFloatPriceInformationCommodityReferenceCalculationPeriod[] calculationPeriodsField;
        
        /// <remarks/>
        public string CommodityReferencePrice {
            get {
                return this.commodityReferencePriceField;
            }
            set {
                this.commodityReferencePriceField = value;
            }
        }
        
        /// <remarks/>
        public IndexCommodityType IndexCommodity {
            get {
                return this.indexCommodityField;
            }
            set {
                this.indexCommodityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string IndexCurrencyUnit {
            get {
                return this.indexCurrencyUnitField;
            }
            set {
                this.indexCurrencyUnitField = value;
            }
        }
        
        /// <remarks/>
        public UnitOfMeasureType IndexCapacityUnit {
            get {
                return this.indexCapacityUnitField;
            }
            set {
                this.indexCapacityUnitField = value;
            }
        }
        
        /// <remarks/>
        public decimal Factor {
            get {
                return this.factorField;
            }
            set {
                this.factorField = value;
            }
        }
        
        /// <remarks/>
        public decimal Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultiplierSpecified {
            get {
                return this.multiplierFieldSpecified;
            }
            set {
                this.multiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal IndexCap {
            get {
                return this.indexCapField;
            }
            set {
                this.indexCapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexCapSpecified {
            get {
                return this.indexCapFieldSpecified;
            }
            set {
                this.indexCapFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal IndexFloor {
            get {
                return this.indexFloorField;
            }
            set {
                this.indexFloorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexFloorSpecified {
            get {
                return this.indexFloorFieldSpecified;
            }
            set {
                this.indexFloorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CRCapacityConversionRate {
            get {
                return this.cRCapacityConversionRateField;
            }
            set {
                this.cRCapacityConversionRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CRCapacityConversionRateSpecified {
            get {
                return this.cRCapacityConversionRateFieldSpecified;
            }
            set {
                this.cRCapacityConversionRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FXInformation FXInformation {
            get {
                return this.fXInformationField;
            }
            set {
                this.fXInformationField = value;
            }
        }
        
        /// <remarks/>
        public BrokerConfirmationFloatPriceInformationCommodityReferenceSpreadInformation SpreadInformation {
            get {
                return this.spreadInformationField;
            }
            set {
                this.spreadInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CalculationPeriod", IsNullable=false)]
        public BrokerConfirmationFloatPriceInformationCommodityReferenceCalculationPeriod[] CalculationPeriods {
            get {
                return this.calculationPeriodsField;
            }
            set {
                this.calculationPeriodsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum IndexCommodityType {
        
        /// <remarks/>
        Canola,
        
        /// <remarks/>
        Cocoa,
        
        /// <remarks/>
        Coffee,
        
        /// <remarks/>
        Corn,
        
        /// <remarks/>
        Cotton,
        
        /// <remarks/>
        Livestock,
        
        /// <remarks/>
        Milk,
        
        /// <remarks/>
        Oats,
        
        /// <remarks/>
        Orange_Juice,
        
        /// <remarks/>
        Rubber,
        
        /// <remarks/>
        Soyabeans,
        
        /// <remarks/>
        Sugar,
        
        /// <remarks/>
        Sunflower_Seeds,
        
        /// <remarks/>
        Wheat,
        
        /// <remarks/>
        Wool,
        
        /// <remarks/>
        Benzene,
        
        /// <remarks/>
        Coal,
        
        /// <remarks/>
        Diesel_Fuel,
        
        /// <remarks/>
        Electricity,
        
        /// <remarks/>
        Fuel_Oil,
        
        /// <remarks/>
        Gas_Oil,
        
        /// <remarks/>
        Gasoline,
        
        /// <remarks/>
        Heating_Oil,
        
        /// <remarks/>
        Jet_Fuel,
        
        /// <remarks/>
        Methanol,
        
        /// <remarks/>
        Naphtha,
        
        /// <remarks/>
        Nat_Gas,
        
        /// <remarks/>
        NGL,
        
        /// <remarks/>
        Oil,
        
        /// <remarks/>
        Ultra_Low_Sulphur_Diesel,
        
        /// <remarks/>
        EUA,
        
        /// <remarks/>
        CER,
        
        /// <remarks/>
        Emissions,
        
        /// <remarks/>
        Time_Charter,
        
        /// <remarks/>
        Wet_Freight,
        
        /// <remarks/>
        Dry_Freight,
        
        /// <remarks/>
        Aluminum,
        
        /// <remarks/>
        Copper,
        
        /// <remarks/>
        Gold,
        
        /// <remarks/>
        Lead,
        
        /// <remarks/>
        Nickel,
        
        /// <remarks/>
        Palladium,
        
        /// <remarks/>
        Platinum,
        
        /// <remarks/>
        Silver,
        
        /// <remarks/>
        Steel,
        
        /// <remarks/>
        Tin,
        
        /// <remarks/>
        Zinc,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationFloatPriceInformationCommodityReferenceSpreadInformation {
        
        private string spreadPayerField;
        
        private decimal spreadAmountField;
        
        private string spreadCurrencyUnitField;
        
        private FXInformation fXInformationField;
        
        /// <remarks/>
        public string SpreadPayer {
            get {
                return this.spreadPayerField;
            }
            set {
                this.spreadPayerField = value;
            }
        }
        
        /// <remarks/>
        public decimal SpreadAmount {
            get {
                return this.spreadAmountField;
            }
            set {
                this.spreadAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string SpreadCurrencyUnit {
            get {
                return this.spreadCurrencyUnitField;
            }
            set {
                this.spreadCurrencyUnitField = value;
            }
        }
        
        /// <remarks/>
        public FXInformation FXInformation {
            get {
                return this.fXInformationField;
            }
            set {
                this.fXInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationFloatPriceInformationCommodityReferenceCalculationPeriod {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationEUATradeDetails {
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private System.DateTime emissionsDeliveryDateField;
        
        private bool emissionsDeliveryDateFieldSpecified;
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EmissionsDeliveryDate {
            get {
                return this.emissionsDeliveryDateField;
            }
            set {
                this.emissionsDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmissionsDeliveryDateSpecified {
            get {
                return this.emissionsDeliveryDateFieldSpecified;
            }
            set {
                this.emissionsDeliveryDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationPhysicalCoalTradeDetails {
        
        private string rSSField;
        
        private string originField;
        
        private string incotermsField;
        
        /// <remarks/>
        public string RSS {
            get {
                return this.rSSField;
            }
            set {
                this.rSSField = value;
            }
        }
        
        /// <remarks/>
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public string Incoterms {
            get {
                return this.incotermsField;
            }
            set {
                this.incotermsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationHubCodificationInformation {
        
        private string buyerHubCodeField;
        
        private string sellerHubCodeField;
        
        /// <remarks/>
        public string BuyerHubCode {
            get {
                return this.buyerHubCodeField;
            }
            set {
                this.buyerHubCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SellerHubCode {
            get {
                return this.sellerHubCodeField;
            }
            set {
                this.sellerHubCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationOptionDetails {
        
        private OptionType optionsTypeField;
        
        private string optionWriterField;
        
        private string optionHolderField;
        
        private OptionStyleType optionStyleField;
        
        private decimal strikePriceField;
        
        private IndexStrikePriceStyleType indexStrikePriceStyleField;
        
        private bool indexStrikePriceStyleFieldSpecified;
        
        private decimal secondStrikePriceField;
        
        private bool secondStrikePriceFieldSpecified;
        
        private decimal cappedPriceField;
        
        private bool cappedPriceFieldSpecified;
        
        private decimal flooredPriceField;
        
        private bool flooredPriceFieldSpecified;
        
        private string optionCurrencyField;
        
        private decimal premiumRateField;
        
        private bool premiumRateFieldSpecified;
        
        private string premiumCurrencyField;
        
        private BrokerConfirmationOptionDetailsPremiumUnit premiumUnitField;
        
        private decimal totalPremiumValueField;
        
        private System.DateTime premiumPaymentDateField;
        
        private bool premiumPaymentDateFieldSpecified;
        
        private System.DateTime exerciseDateTimeField;
        
        private bool exerciseDateTimeFieldSpecified;
        
        private BrokerConfirmationOptionDetailsExercise[] exerciseScheduleField;
        
        /// <remarks/>
        public OptionType OptionsType {
            get {
                return this.optionsTypeField;
            }
            set {
                this.optionsTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OptionWriter {
            get {
                return this.optionWriterField;
            }
            set {
                this.optionWriterField = value;
            }
        }
        
        /// <remarks/>
        public string OptionHolder {
            get {
                return this.optionHolderField;
            }
            set {
                this.optionHolderField = value;
            }
        }
        
        /// <remarks/>
        public OptionStyleType OptionStyle {
            get {
                return this.optionStyleField;
            }
            set {
                this.optionStyleField = value;
            }
        }
        
        /// <remarks/>
        public decimal StrikePrice {
            get {
                return this.strikePriceField;
            }
            set {
                this.strikePriceField = value;
            }
        }
        
        /// <remarks/>
        public IndexStrikePriceStyleType IndexStrikePriceStyle {
            get {
                return this.indexStrikePriceStyleField;
            }
            set {
                this.indexStrikePriceStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexStrikePriceStyleSpecified {
            get {
                return this.indexStrikePriceStyleFieldSpecified;
            }
            set {
                this.indexStrikePriceStyleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SecondStrikePrice {
            get {
                return this.secondStrikePriceField;
            }
            set {
                this.secondStrikePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondStrikePriceSpecified {
            get {
                return this.secondStrikePriceFieldSpecified;
            }
            set {
                this.secondStrikePriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CappedPrice {
            get {
                return this.cappedPriceField;
            }
            set {
                this.cappedPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CappedPriceSpecified {
            get {
                return this.cappedPriceFieldSpecified;
            }
            set {
                this.cappedPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal FlooredPrice {
            get {
                return this.flooredPriceField;
            }
            set {
                this.flooredPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlooredPriceSpecified {
            get {
                return this.flooredPriceFieldSpecified;
            }
            set {
                this.flooredPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string OptionCurrency {
            get {
                return this.optionCurrencyField;
            }
            set {
                this.optionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public decimal PremiumRate {
            get {
                return this.premiumRateField;
            }
            set {
                this.premiumRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumRateSpecified {
            get {
                return this.premiumRateFieldSpecified;
            }
            set {
                this.premiumRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string PremiumCurrency {
            get {
                return this.premiumCurrencyField;
            }
            set {
                this.premiumCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public BrokerConfirmationOptionDetailsPremiumUnit PremiumUnit {
            get {
                return this.premiumUnitField;
            }
            set {
                this.premiumUnitField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalPremiumValue {
            get {
                return this.totalPremiumValueField;
            }
            set {
                this.totalPremiumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PremiumPaymentDate {
            get {
                return this.premiumPaymentDateField;
            }
            set {
                this.premiumPaymentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumPaymentDateSpecified {
            get {
                return this.premiumPaymentDateFieldSpecified;
            }
            set {
                this.premiumPaymentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExerciseDateTime {
            get {
                return this.exerciseDateTimeField;
            }
            set {
                this.exerciseDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExerciseDateTimeSpecified {
            get {
                return this.exerciseDateTimeFieldSpecified;
            }
            set {
                this.exerciseDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Exercise", IsNullable=false)]
        public BrokerConfirmationOptionDetailsExercise[] ExerciseSchedule {
            get {
                return this.exerciseScheduleField;
            }
            set {
                this.exerciseScheduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum OptionType {
        
        /// <remarks/>
        Call,
        
        /// <remarks/>
        Put,
        
        /// <remarks/>
        Capped_Call,
        
        /// <remarks/>
        Floored_Put,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum OptionStyleType {
        
        /// <remarks/>
        American,
        
        /// <remarks/>
        European,
        
        /// <remarks/>
        Asian,
        
        /// <remarks/>
        Cap,
        
        /// <remarks/>
        Floor,
        
        /// <remarks/>
        Collar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum IndexStrikePriceStyleType {
        
        /// <remarks/>
        Index_Following,
        
        /// <remarks/>
        Index_Dated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationOptionDetailsPremiumUnit {
        
        private string currencyField;
        
        private UnitOfMeasureType capacityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public UnitOfMeasureType Capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationOptionDetailsExercise {
        
        private System.DateTime deliveryStartDateTimeField;
        
        private bool deliveryStartDateTimeFieldSpecified;
        
        private System.DateTime deliveryEndDateTimeField;
        
        private bool deliveryEndDateTimeFieldSpecified;
        
        private System.DateTime exerciseDateTimeField;
        
        private string exerciseTimeZoneField;
        
        /// <remarks/>
        public System.DateTime DeliveryStartDateTime {
            get {
                return this.deliveryStartDateTimeField;
            }
            set {
                this.deliveryStartDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryStartDateTimeSpecified {
            get {
                return this.deliveryStartDateTimeFieldSpecified;
            }
            set {
                this.deliveryStartDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeliveryEndDateTime {
            get {
                return this.deliveryEndDateTimeField;
            }
            set {
                this.deliveryEndDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryEndDateTimeSpecified {
            get {
                return this.deliveryEndDateTimeFieldSpecified;
            }
            set {
                this.deliveryEndDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExerciseDateTime {
            get {
                return this.exerciseDateTimeField;
            }
            set {
                this.exerciseDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ExerciseTimeZone {
            get {
                return this.exerciseTimeZoneField;
            }
            set {
                this.exerciseTimeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationDeliveryPeriod {
        
        private System.DateTime deliveryPeriodStartDateField;
        
        private System.DateTime deliveryPeriodEndDateField;
        
        private decimal deliveryPeriodNotionalQuantityField;
        
        private decimal fixedPriceField;
        
        private bool fixedPriceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DeliveryPeriodStartDate {
            get {
                return this.deliveryPeriodStartDateField;
            }
            set {
                this.deliveryPeriodStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DeliveryPeriodEndDate {
            get {
                return this.deliveryPeriodEndDateField;
            }
            set {
                this.deliveryPeriodEndDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal DeliveryPeriodNotionalQuantity {
            get {
                return this.deliveryPeriodNotionalQuantityField;
            }
            set {
                this.deliveryPeriodNotionalQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal FixedPrice {
            get {
                return this.fixedPriceField;
            }
            set {
                this.fixedPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FixedPriceSpecified {
            get {
                return this.fixedPriceFieldSpecified;
            }
            set {
                this.fixedPriceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationAgent {
        
        private AgentType agentTypeField;
        
        private string agentNameField;
        
        private object itemField;
        
        /// <remarks/>
        public AgentType AgentType {
            get {
                return this.agentTypeField;
            }
            set {
                this.agentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AgentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Broker", typeof(BrokerConfirmationAgentBroker))]
        [System.Xml.Serialization.XmlElementAttribute("ECVNA", typeof(BrokerConfirmationAgentECVNA))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum AgentType {
        
        /// <remarks/>
        Broker,
        
        /// <remarks/>
        ECVNA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationAgentBroker {
        
        private string brokerIDField;
        
        private decimal totalFeeField;
        
        private string feeCurrencyField;
        
        private CommonPricingType sleeveField;
        
        private bool sleeveFieldSpecified;
        
        private CommonPricingType voiceField;
        
        private bool voiceFieldSpecified;
        
        private CommonPricingType initiateField;
        
        private bool initiateFieldSpecified;
        
        private CommonPricingType spreadField;
        
        private bool spreadFieldSpecified;
        
        private string brokerSpreadIDField;
        
        private string brokerTradeIDField;
        
        /// <remarks/>
        public string BrokerID {
            get {
                return this.brokerIDField;
            }
            set {
                this.brokerIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalFee {
            get {
                return this.totalFeeField;
            }
            set {
                this.totalFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string FeeCurrency {
            get {
                return this.feeCurrencyField;
            }
            set {
                this.feeCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public CommonPricingType Sleeve {
            get {
                return this.sleeveField;
            }
            set {
                this.sleeveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SleeveSpecified {
            get {
                return this.sleeveFieldSpecified;
            }
            set {
                this.sleeveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CommonPricingType Voice {
            get {
                return this.voiceField;
            }
            set {
                this.voiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VoiceSpecified {
            get {
                return this.voiceFieldSpecified;
            }
            set {
                this.voiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CommonPricingType Initiate {
            get {
                return this.initiateField;
            }
            set {
                this.initiateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InitiateSpecified {
            get {
                return this.initiateFieldSpecified;
            }
            set {
                this.initiateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CommonPricingType Spread {
            get {
                return this.spreadField;
            }
            set {
                this.spreadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpreadSpecified {
            get {
                return this.spreadFieldSpecified;
            }
            set {
                this.spreadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string BrokerSpreadID {
            get {
                return this.brokerSpreadIDField;
            }
            set {
                this.brokerSpreadIDField = value;
            }
        }
        
        /// <remarks/>
        public string BrokerTradeID {
            get {
                return this.brokerTradeIDField;
            }
            set {
                this.brokerTradeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BrokerConfirmationAgentECVNA {
        
        private string bSCPartyIDField;
        
        private EnergyAccountType buyerEnergyAccountField;
        
        private bool buyerEnergyAccountFieldSpecified;
        
        private EnergyAccountType sellerEnergyAccountField;
        
        private bool sellerEnergyAccountFieldSpecified;
        
        private string sellerIDField;
        
        private string buyerIDField;
        
        /// <remarks/>
        public string BSCPartyID {
            get {
                return this.bSCPartyIDField;
            }
            set {
                this.bSCPartyIDField = value;
            }
        }
        
        /// <remarks/>
        public EnergyAccountType BuyerEnergyAccount {
            get {
                return this.buyerEnergyAccountField;
            }
            set {
                this.buyerEnergyAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuyerEnergyAccountSpecified {
            get {
                return this.buyerEnergyAccountFieldSpecified;
            }
            set {
                this.buyerEnergyAccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EnergyAccountType SellerEnergyAccount {
            get {
                return this.sellerEnergyAccountField;
            }
            set {
                this.sellerEnergyAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SellerEnergyAccountSpecified {
            get {
                return this.sellerEnergyAccountFieldSpecified;
            }
            set {
                this.sellerEnergyAccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SellerID {
            get {
                return this.sellerIDField;
            }
            set {
                this.sellerIDField = value;
            }
        }
        
        /// <remarks/>
        public string BuyerID {
            get {
                return this.buyerIDField;
            }
            set {
                this.buyerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.efet.org/schemas/eCM/V4R0/EFET-CoreCmpts-V4R0.xsd")]
    public enum EnergyAccountType {
        
        /// <remarks/>
        Production,
        
        /// <remarks/>
        Consumption,
    }
}
