kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}{{ .Values.type.configmap }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.environment }}
  TRADECUBE_SERVICES_HTTPS_PORT: '{{ .Values.port.servicesSsl }}'
  TRADECUBE_SERVICES_CERT_NAME: {{ .Values.env.certificateNamePrefix }}{{ .Values.env.certificateNameSuffix }}
  TRADECUBE_SERVICES_CERT_PASSWORD: '{{ .Values.env.certPassword }}'
  TRADECUBE_SERVICES_CONNECTION_STRING: {{ .Values.env.loggingConnectionString }} 
  TRADECUBE_SERVICES_LOGGING_COLLECTION: {{ .Values.env.loggingCollection }}
  TRADECUBE_SERVICES_REDIS_HOSTS:  {{ .Values.env.redisHosts }}
  TRADECUBE_SERVICES_REDIS_PASSWORD: {{ .Values.env.redisPassword }}
  TRADECUBE_API_DOMAIN: {{ .Values.env.apiDomain }}
  TRADECUBE_API_PORT: '{{ .Values.env.apiPort }}'
  TLS_SECRET_NAME: {{ .Release.Name }}{{ .Values.type.certificate }}{{ .Values.type.secret }}
  PFX_CERTIFICATE_NAME: {{ .Values.env.certificateNameSuffix }}
  PFX_SECRET_NAME: {{ .Release.Name }}{{ .Values.type.secret }}
  JSREPORT_DOMAIN: {{ .Values.env.jsreportDomain }}
  JSREPORT_PORT: '{{ .Values.env.jsreportPort }}'
  JSREPORT_USERNAME: {{ .Values.env.jsreportUsername }}
  JSREPORT_PASSWORD: '{{ .Values.env.jsreportPassword }}'
  EQUIAS_REQUEST_TOKEN_URI: '{{ .Values.equias.requestTokenURI }}'
  EQUIAS_GET_TRADE_STATUS_URI: '{{ .Values.equias.getTradeStatusURI }}'
  EQUIAS_ADD_PHYSICAL_TRADE_URI: '{{ .Values.equias.addPhysicalTradeURI }}'
  EQUIAS_MODIFY_PHYSICAL_TRADE_URI: '{{ .Values.equias.modifyPhysicalTradeURI }}'
  EQUIAS_CANCEL_TRADE_URI: '{{ .Values.equias.cancelTradeURI }}'
  FIDECTUS_CONFIRMATION_URI: {{ .Values.fidectus.confirmationURI }}
  FIDECTUS_CONFIRMATION_BOX_RESULT_URI: {{ .Values.fidectus.confirmationBoxResultURI }}