apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}{{ .Values.component.services }}{{ .Values.type.service }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: Tradecube
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ .Release.Name }}{{ .Values.component.services }}
  ports:
  - port: {{ .Values.service.httpsPort }}
    targetPort: {{ .Values.port.servicesSsl }}
    protocol: {{ .Values.service.protocol }}
    name: https