kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}{{ .Values.type.configmap }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:  
  TRADECUBE_SERVICES_HTTPS_PORT: '{{ .Values.port.servicesSsl }}'
  TRADECUBE_SERVICES_CERT_NAME: {{ .Values.env.certFile }}
  TRADECUBE_SERVICES_CERT_PASSWORD: '{{ .Values.env.certPassword }}'
  TRADECUBE_API_DOMAIN: {{ .Values.env.apiDomain }}
  TRADECUBE_API_PORT: '{{ .Values.env.apiPort }}'
  JSREPORT_DOMAIN: {{ .Values.env.jsreportDomain }}
  JSREPORT_PORT: '{{ .Values.env.jsreportPort }}'
  EQUIAS_REQUEST_TOKEN_URI: '{{ .Values.equias.requestTokenURI }}'
  EQUIAS_GET_TRADE_STATUS_URI: '{{ .Values.equias.getTradeStatusURI }}'
  EQUIAS_ADD_PHYSICAL_TRADE_URI: '{{ .Values.equias.addPhysicalTradeURI }}'
  EQUIAS_MODIFY_PHYSICAL_TRADE_URI: '{{ .Values.equias.modifyPhysicalTradeURI }}'